package com.cg.yangaiagent.tools;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

@SpringBootTest
@ActiveProfiles("local")
public class PdfToolTest {

    @Autowired
    private PdfTool pdfTool;

    @Test
    void testEnglishOnly() {
        String content = "Hello World!\n\nThis is a test PDF generated by OpenPDF.";
        String result = pdfTool.saveTextAsPdf(content, "English Test", "test_english_only");
        System.out.println(result);
    }

    @Test
    void testSaveUrl() {
        String result = pdfTool.saveUrlAsPdf("https://www.baidu.com", "baidu_homepage");
        System.out.println("网页转PDF结果：\n" + result);
    }
}